# Generated by Django 5.1.1 on 2024-09-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_document_content_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='base64',
            field=models.TextField(blank=True),
        ),
    ]
