# Generated by Django 5.1.1 on 2024-09-24 16:27

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_page_unique_page_per_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='embeddings',
        ),
        migrations.CreateModel(
            name='PageEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=128)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='api.page')),
            ],
        ),
    ]
