# Generated by Django 5.1.1 on 2024-09-27 19:04

import pgvector.django.halfvec
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_query_queryembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageembedding',
            name='half_embedding',
            field=pgvector.django.halfvec.HalfVectorField(dimensions=128, null=True),
        ),
        migrations.AddField(
            model_name='queryembedding',
            name='half_embedding',
            field=pgvector.django.halfvec.HalfVectorField(dimensions=128, null=True),
        ),
    ]
