# Generated by Django 5.1.1 on 2024-09-29 21:25

import django.db.models.deletion
import pgvector.django.halfvec
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_pageembedding_half_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryembedding',
            name='embedding',
            field=pgvector.django.halfvec.HalfVectorField(dimensions=128),
        ),
        migrations.AlterField(
            model_name='queryembedding',
            name='query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='api.query'),
        ),
    ]
