# Generated by Django 5.1.1 on 2024-09-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_queryembedding_embedding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryembedding',
            name='query',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
        migrations.DeleteModel(
            name='QueryEmbedding',
        ),
    ]
