# Generated by Django 5.1.1 on 2024-09-20 23:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_collection_per_user'),
        ),
    ]
