# Generated by Django 5.1.1 on 2024-09-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_base64_page_img_base64_document_base64_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='page',
            name='unique_page_per_document',
        ),
    ]
