# Generated by Django 5.1.1 on 2024-09-27 19:04

from django.db import migrations


def populate_halfvec_fields(apps, schema_editor):
    PageEmbedding = apps.get_model("api", "PageEmbedding")
    QueryEmbedding = apps.get_model("api", "QueryEmbedding")

    for pe in PageEmbedding.objects.all():
        pe.half_embedding = pe.embedding
        pe.save()

    for qe in QueryEmbedding.objects.all():
        qe.half_embedding = qe.embedding
        qe.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_pageembedding_half_embedding_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_halfvec_fields),
    ]
