# Generated by Django 5.1.1 on 2024-10-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_collection_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['name', 'collection'], name='document_name_collection_idx'),
        ),
    ]
