# Generated by Django 5.1.1 on 2024-10-15 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_document_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.CheckConstraint(condition=models.Q(('name', 'all'), _negated=True), name='collection_name_not_all'),
        ),
    ]
