# Generated by Django 5.1.1 on 2024-11-02 23:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_collection_collection_name_not_all"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="s3_file",
            field=models.FileField(blank=True, upload_to=api.models.get_upload_path),
        ),
    ]
