# Generated by Django 5.1.3 on 2024-11-19 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_update_max_sim_function"),
    ]

    operations = []
