# Generated by Django 5.1.3 on 2024-11-18 21:13

import pgvector.django.bit
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_bit_max_sim_function"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageembedding",
            name="bit_embedding",
            field=pgvector.django.bit.BitField(null=True),
        ),
    ]
