# Generated by Django 5.1.3 on 2024-11-18 21:56

import pgvector.django.bit
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0026_pageembedding_bit_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageembedding",
            name="bit_embedding",
            field=pgvector.django.bit.BitField(length=128, null=True),
        ),
    ]
