# Generated by Django 5.1.3 on 2024-11-19 01:55

from django.db import migrations


def populate_bits(apps, schema_editor):
    PageEmbedding = apps.get_model("api", "PageEmbedding")

    for page_embedding in PageEmbedding.objects.all():
        page_embedding.save()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_alter_pageembedding_bit_embedding"),
    ]

    operations = [
        migrations.RunPython(populate_bits, reverse_code=migrations.RunPython.noop),
    ]
