# Generated by Django 5.1.3 on 2024-11-19 04:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_auto_20241119_0226"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION cosine_max_sim(document halfvec[], query halfvec[]) RETURNS double precision AS $$
                WITH queries AS (
                    SELECT row_number() OVER () AS query_number, * FROM (SELECT unnest(query) AS query)
                ),
                documents AS (
                    SELECT unnest(document) AS document
                ),
                similarities AS (
                    SELECT query_number, 1 - (document <=> query) AS similarity FROM queries CROSS JOIN documents
                ),
                max_similarities AS (
                    SELECT MAX(similarity) AS max_similarity FROM similarities GROUP BY query_number
                )
                SELECT SUM(max_similarity) FROM max_similarities
            $$ LANGUAGE SQL
            """
        )
    ]
