# Generated by Django 5.1.1 on 2024-11-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='svix_application_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
